### ISSUE TITLE
[Compatibility with CIT resewn]CIT resourcepacks for axolotl buckets do not work

### ISSUE THREAD

**Issue by ghost** [AkashiiKun/MoreAxolotlVariantsAPI-Common#10]
I guess the reason is that mavapi changes the "Variant" nbt of axolotl buckets
Is it possible to fix CIT resourcepacks without modifying them?Such as an option to disable the modifications to the "Variant" NBT of Vanilla Variant axolotls.

**Comment by AkashiiKun** [comment]
MAVAPI has a feature that adds custom textures for the buckets of each variant. Can be modified through resourcepacks.

**Comment by AkashiiKun** [comment]
https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/tree/master/Common/src/main/resources/assets/mavapi

**Comment by ghost** [comment]
> https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/tree/master/Common/src/main/resources/assets/mavapi

This is indeed a solution.But CIT reswen also provided the abilitiy to custom the textures of axolotls bucket according to NBT.If someone would like to enjoy existing CIT resourcepacks,The resourcepack must be modified to adapt the nbt changes in mavapi,or they will not work.
![)W}QN@OUH 2F8M5PMG2VKJW](https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/assets/129179911/9158022a-43cd-4481-aaf8-6a4e70e81d21)

But many advanced optifine resourcepacks used CIT feature,It would be a troublesome thing to check and edit every resourcepack.So if there is an option to disabled the nbt changes for vanilla axolotls,these resourcepack will work properly without any changes.

**Comment by AkashiiKun** [comment]
The variant has been changed from an id to an identifier for modded variants compatibility.

**Comment by AkashiiKun** [comment]
Which is the purpose of this API, to be used to add variants.

**Comment by AkashiiKun** [comment]
And no, we aren't going to change the nbt system. You can use the identifier as it's a valid nbt value.
minecraft:luci instead of 0 for example

**Comment by ghost** [comment]
Sorry for keeping you waiting

There are two types of axolotl buckets can be obtained by using /give command when you install mavapi.(/give @p minecraft:axolotl_bucket{Variant:2} and /give @p minecraft:axolotl_bucket{Variant: "minecraft:gold"}  )Former bucket can be affected by CIT resourcepack,the latter cannot.
![image](https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/assets/129179911/05fae9b7-6a3d-41a7-9aec-3930929f1eee)

https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/assets/129179911/0ebf6f69-bc48-4509-9ba7-479ebe9fafb6


If the game can give player the Former bucket when they catched corresponding vanilla axolotl(Optional),we may resolve this issue without breaking existing nbt system

I'm not sure how difficult it is to implement this feature,but it seems to be feasible.

**Comment by ghost** [comment]
> And no, we aren't going to change the nbt system. You can use the identifier as it's a valid nbt value. minecraft:luci instead of 0 for example

Okay.If this method is invalid or inconvenient to implement,please close this issue:)
