### ISSUE TITLE
Summon command not working

### ISSUE THREAD

**Issue by gaywaffles049** [AkashiiKun/MoreAxolotlVariantsAPI-Common#12]
Whenever I type the /summon minecraft:axolotl [pos] {Variant:"mavm<name>"} no matter what name I put in the brackets it just comes out as the pink one, the only thing I am doing differently is changing my coords in the [pos] section. And it won't let me type it with bracets so I take those off. But nothing is working. I play on version 1.20.1 so the old way of summoning wouldn't work either. Any help would be appcitated.

**Comment by AkashiiKun** [comment]
Will just give an example
/summon minecraft:axolotl ~ ~ ~ {Variant:"minecraft:blue"}

**Comment by gaywaffles049** [comment]
Yes exactly like that but instead it's like your commands, like your variants like Shulk or wilder
