### ISSUE TITLE
Mixin can‘t apply mavapi

### ISSUE THREAD

**Issue by JamesBraker** [AkashiiKun/MoreAxolotlVariantsAPI-Common#16]
The current game cannot continue to run because the Mixin cannot apply the mavapi mod.
（Original Simplified Chinese text: 当前游戏因为Mixin无法应用mavapi模组，无法继续运行。）

Minecraft:1.21
Fabric:0.15.11
Fabric API:0.100.4
mavm:1.3.0 (for MC1.21)
mavapi:1.2.0 (for MC1.21)

Can confirm the crash is NOT related to other mods.Loading ONLY mavapi+mavm can crash the game.

[crash-2024-07-04_15.42.17-client.txt](https://github.com/user-attachments/files/16095253/crash-2024-07-04_15.42.17-client.txt)

Plz reply if in need of any extra information.

**Comment by AkashiiKun** [comment]
Fixed in version 1.2.1.

**Comment by JamesBraker** [comment]
Thanks!!
