### ISSUE TITLE
Error: java.lang.BootstrapMethodError

### ISSUE THREAD

**Issue by AtheisticPanda** [AkashiiKun/MoreAxolotlVariantsAPI-Common#19]
The game crashed whilst bootstrap
Error: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5762 failed

This is happening whenever I open either API or MAVM
[crash-2024-12-06_23.55.35-client.txt](https://github.com/user-attachments/files/18046305/crash-2024-12-06_23.55.35-client.txt)
[crash-2024-12-06_23.56.52-client.txt](https://github.com/user-attachments/files/18046306/crash-2024-12-06_23.56.52-client.txt)

**Comment by AtheisticPanda** [comment]
Sorry this is the newest 1.21.4 download

**Comment by AkashiiKun** [comment]
Solved, new update for both mods incoming with a fix.

**Comment by AtheisticPanda** [comment]
Thanks AkashiiKun! You're awesome!

**Comment by AkashiiKun** [comment]
Thanks for reporting. A lot of people downloaded it but didn't report it wasn't working. It was working in development but for some reason in production the mod was missing an important part that makes mixins to work properly.
