### ISSUE TITLE
I know it’s years old but do you have the original caves and cliffs part 2 mod code since I want to try and make a mod to work with it but using multinoise

### ISSUE THREAD

**Issue by Danjhop4** [AkashiiKun/MoreAxolotlVariantsAPI-Common#3]
There is no GitHub source for it 
I only can see the compiled names the bit for 3D biomes seems simple to it’s changing 2d to use 3D cords and blockpos

**Comment by AkashiiKun** [comment]
No, also you could just message me in CurseForge instead of here.

**Comment by Danjhop4** [comment]
> No, also you could just message me in CurseForge instead of here.

Can’t make an account
