### ISSUE TITLE
Mod is requesting 'javafml' 46 on 1.19.2, which has version 43

### ISSUE THREAD

**Issue by brisingraerowing** [AkashiiKun/MoreAxolotlVariantsAPI-Common#4]
As per title. This causes a startup crash. Mod version 1.1.0

**Comment by SimplyTraier** [comment]
Getting this crash as well, along with Mav (More axolotl variants) thinking that I don't have it installed, I think someone might have uploaded the wrong version for 1.19.2

**Comment by DomiIRL** [comment]
1.19.2 backport of  1.1.0 has an issue. Gonna reupload a fixed version soon.
Old version of 1.19.2 works fine with mavm since mavm doesn't use any new features.
