### ISSUE TITLE
Mixins crash on launch

### ISSUE THREAD

**Issue by Castafers** [AkashiiKun/MoreAxolotlVariantsAPI-Common#8]
I'm unsure of what this all means, however. Removing the MAVAPI mods fixed my crashing.

[crash-2023-08-15_05.50.41-client.txt](https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/files/12344389/crash-2023-08-15_05.50.41-client.txt)

https://mclo.gs/udPgIFr#L481

**Comment by carson-coder** [comment]
Could you see what is the minimum amount of mods needed to reproduce this

**Comment by AkashiiKun** [comment]
I've tried with just MAVM and MAVAPI and it crashes indeed
